/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#404696",
        "secondary-fixed-dim": "#ffb59e",
        "on-secondary-fixed-variant": "#842400",
        "on-background": "#e2e2e8",
        "background": "#111318",
        "on-primary-fixed": "#001f28",
        "surface": "#111318",
        "surface-tint": "#4cd6ff",
        "outline-variant": "#3c494e",
        "on-primary": "#003543",
        "tertiary": "#d8d9ff",
        "surface-container": "#1e2024",
        "surface-dim": "#111318",
        "surface-bright": "#37393e",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "surface-container-highest": "#333539",
        "on-primary-container": "#00566a",
        "secondary-fixed": "#ffdbd0",
        "on-secondary": "#5e1700",
        "surface-variant": "#333539",
        "on-primary-fixed-variant": "#004e60",
        "tertiary-fixed": "#e0e0ff",
        "on-secondary-fixed": "#3a0b00",
        "surface-container-lowest": "#0c0e12",
        "secondary": "#ffb59e",
        "on-surface-variant": "#bbc9cf",
        "primary-fixed-dim": "#4cd6ff",
        "outline": "#859399",
        "tertiary-fixed-dim": "#bec2ff",
        "primary-fixed": "#b7eaff",
        "primary": "#a4e6ff",
        "inverse-surface": "#e2e2e8",
        "on-tertiary-fixed": "#050962",
        "on-tertiary-fixed-variant": "#383e8e",
        "secondary-container": "#b13401",
        "on-tertiary": "#202676",
        "error": "#ffb4ab",
        "on-surface": "#e2e2e8",
        "inverse-on-surface": "#2f3035",
        "tertiary-container": "#b7bbff",
        "error-container": "#93000a",
        "surface-container-low": "#1a1c20",
        "surface-container-high": "#282a2e",
        "inverse-primary": "#00677f",
        "on-secondary-container": "#ffd3c6",
        "primary-container": "#00d1ff"
      },
      fontFamily: {
        "headline": ["Barlow Condensed", "sans-serif"],
        "body": ["Barlow Condensed", "sans-serif"],
        "label": ["Barlow Condensed", "sans-serif"],
        "sans": ["Barlow Condensed", "sans-serif"]
      },
      borderRadius: {
        "sm": "12px",
        "DEFAULT": "16px",
        "lg": "20px",
        "xl": "24px",
        "2xl": "32px",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
